This dats was taken from the **ERASE-MM Community Vital Signs Project**, developed by Professor Michael Kramer. 
Access to full data dictionary: https://drive.google.com/file/d/1PWz21DJYbl7BLgxxympxaS6qqSpnPzaP/view 

    "PCPrate": "Primary care physician's per capita [county]",
    "pctNOIns_Fem": "% Uninsured women [census tract]",
    "pctOBESE": "% Obesity [county]",
    "FI": "% Food insecure [county]",
    "OBGYNrate": "OB-GYN per capita [county]",
    "MIDWIVESrate": "Nurse midwives per capita [county]",
    "rtSTD": "Chlamydia rate [county]",
    "rtTEENBIRTH": "Teen birth rate [county]",
    "MHPROVIDERrate": "Mental health providers per capita [county]",
    "MHCENTERrate": "Mental health centers per capita",
    "rtDRUGODMORTALITY": "Drug overdose mortality [county]",
    "pctNoVehicle": "% Households without car [census tract / county]",
    "pctRural": "% Rural [county]",
    "rtSocASSOC": "Social associations per capita [county]",
    "pctSPHH": "% Households with children, single parent [census tract]",
    "pctMOVE": "% Residential turnover [census tract]",
    "pctOWNER_OCC": "% Owner occupied houses [census tract]",
    "pctOVERCROWDHH": "% Households with overcrowding [census tract]",
    "pctHOUSE_DISTRESS": "% Housing distress [county]",
    "rtVIOLENTCR": "Violent crime rate [county]",
    "segregation": "Racial diversity/segregation [county]",
    "pct_less_well": "% Non-English speakers [neighborhood]",
    "pctPOV": "% Poverty rate [census tract]",
    "ICE_INCOME_all": "Poverty concentration [census tract]",
    "NDI_raw": "Neighborhood Deprivation Index [census tract]",
    "Racialized_pov": "POC Poverty:White Poverty"

This dats was taken from the **ERASE-MM Community Vital Signs Project**, developed by Professor Michael Kramer. 
Access to full data dictionary

In [2]:
import pandas as pd
import os
import glob


folder_path = 'KramerProject'

csv_files = glob.glob(os.path.join(folder_path, '*.csv'))

df_list = [pd.read_csv(file) for file in csv_files]
merged_df = pd.concat(df_list, ignore_index=True)

merged_df.head(15)

,GEOID,YEAR,state,PCPrate,pctOBESE,FI,MIDWIVESrate,OBGYNrate,rtTEENBIRTH,rtSTD,MHCENTERrate,MHPROVIDERrate,rtDRUGODMORTALITY,pctNoVehicle,pctRural,rtSocASSOC,pctHOUSE_DISTRESS,rtVIOLENTCR,segregation,Racialized_pov
0,15001,2022,Hawaii,77.868570,0.252,0.131,5.839700,22.385518,24.208712,373.7,0.0,5.322662,11.059098,0.050326,0.595833,6.649695,0.225040,237.331409,27.088059,1.562700
1,15003,2022,Hawaii,95.215258,0.254,0.105,5.010899,36.537803,16.781270,656.6,0.0,1.401752,18.400058,0.096167,0.013298,6.413131,0.273879,237.652324,38.786594,1.223448
2,15005,2022,Hawaii,0.000000,0.267,0.199,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.093750,1.000000,0.000000,0.000000,0.000000,0.000000,1.625000
3,15007,2022,Hawaii,81.683775,0.249,0.098,2.754138,13.770690,20.160072,336.1,0.0,1.361396,18.957171,0.042780,0.420101,9.682819,0.233296,235.303946,36.705361,0.706158
4,15009,2022,Hawaii,81.597360,0.239,0.103,7.093540,18.916107,19.285220,415.7,0.0,3.044678,16.715553,0.044182,0.210529,7.466386,0.272133,293.272171,40.898224,1.003175
5,5001,2022,Arkansas,53.821313,0.368,0.164,0.000000,11.114816,50.582552,823.5,0.0,0.000000,0.000000,0.096661,0.533041,12.581494,0.121745,472.896287,29.357910,3.914234
6,5003,2022,Arkansas,42.840313,0.391,0.162,0.000000,10.037137,37.959668,610.5,0.0,10.710078,23.711934,0.088546,0.621172,15.261739,0.128869,320.919650,22.116301,1.607854
7,5005,2022,Arkansas,83.048595,0.320,0.162,4.590736,13.772208,31.278332,202.7,0.0,8.304860,17.489049,0.043899,0.598485,9.300773,0.108873,182.387935,24.628180,1.661440
8,5007,2022,Arkansas,58.564755,0.298,0.117,3.453253,17.266267,24.504275,328.9,0.0,0.112363,12.849143,0.028138,0.247763,8.669454,0.117454,274.525753,28.885792,1.825668
9,5009,2022,Arkansas,76.658736,0.324,0.161,5.243564,5.243564,32.681564,259.1,0.0,4.308750,11.551756,0.055497,0.608533,11.220346,0.117014,551.207439,39.654006,2.805925
10,5011,2022,Arkansas,57.647963,0.383,0.173,0.000000,0.000000,34.995626,483.1,0.0,0.000000,0.000000,0.086423,0.489454,13.007526,0.144432,261.402560,18.547837,2.841735
11,5013,2022,Arkansas,21.092596,0.389,0.139,0.000000,0.000000,25.751073,443.2,0.0,0.000000,0.000000,0.032710,1.000000,11.562922,0.111111,211.172970,9.053587,2.904519
12,5015,2022,Arkansas,63.302268,0.339,0.143,7.038288,0.000000,41.913043,257.2,0.0,0.000000,24.741102,0.049573,0.855049,12.684989,0.142025,336.591249,31.956770,1.759021
13,5017,2022,Arkansas,69.867252,0.446,0.212,0.000000,0.000000,46.161322,810.4,0.0,0.000000,0.000000,0.114271,1.000000,9.883376,0.147332,366.781380,54.821024,2.141996
14,5019,2022,Arkansas,56.282538,0.401,0.170,0.000000,25.947068,17.209302,797.5,0.0,0.000000,0.000000,0.062979,0.578531,14.336918,0.131687,329.478363,24.343031,2.512303

In [3]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3144 entries, 0 to 3143
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   GEOID              3144 non-null   int64
 1   YEAR               3144 non-null   int64
 2   state              3144 non-null   object
 3   PCPrate            3144 non-null   float64
 4   pctOBESE           3144 non-null   float64
 5   FI                 3144 non-null   float64
 6   MIDWIVESrate       3144 non-null   float64
 7   OBGYNrate          3144 non-null   float64
 8   rtTEENBIRTH        3144 non-null   float64
 9   rtSTD              3144 non-null   float64
 10  MHCENTERrate       3144 non-null   float64
 11  MHPROVIDERrate     3144 non-null   float64
 12  rtDRUGODMORTALITY  3144 non-null   float64
 13  pctNoVehicle       3144 non-null   float64
 14  pctRural           3144 non-null   float64
 15  rtSocASSOC         3144 non-null   float64
 16  pctHOUSE_DISTRESS  3144 non-null   float64
 17  rtVIOLENTCR        3144 non-null   float64
 18  segregation        3144 non-null   float64
 19  Racialized_pov     3144 non-null   float64
dtypes: float64(17), int64(2), object(1)
memory usage: 491.4+ KB

In [4]:
merged_df.to_csv('merged_kramer_data.csv', index=False)

In [5]:
merged_df['state'].nunique()

51

In [6]:
#Primary care physician's per capita [county] —  PCPrate 

state_pcprate_avg = merged_df.groupby('state')['PCPrate'].mean().reset_index()
state_pcprate_avg = state_pcprate_avg.sort_values(by='PCPrate', ascending=False)
state_pcprate_avg


#❓ to Dhrumil -- can I count the state average like this? -- just counting average counties's rate?

                   state     PCPrate
8   District of Columbia  133.721364
39          Rhode Island  108.482871
19                 Maine   92.931921
29         New Hampshire   91.727925
21         Massachusetts   89.634145
45               Vermont   88.851313
1                 Alaska   78.878799
30            New Jersey   74.636297
37                Oregon   74.592491
6            Connecticut   73.941487
50               Wyoming   68.737818
4             California   68.390258
11                Hawaii   67.272993
38          Pennsylvania   66.409844
20              Maryland   65.979556
7               Delaware   64.430916
5               Colorado   63.887880
23             Minnesota   63.887704
47            Washington   62.632726
49             Wisconsin   62.436152
32              New York   60.348994
16                Kansas   58.031381
22              Michigan   57.780096
46              Virginia   56.509188
48         West Virginia   54.567844
15                  Iowa   54.069139
2                Arizona   53.024389
33        North Carolina   51.962531
27              Nebraska   51.919842
26               Montana   51.302796
31            New Mexico   50.814442
28                Nevada   49.481232
9                Florida   49.370869
40        South Carolina   49.301992
35                  Ohio   49.155343
44                  Utah   47.714093
12                 Idaho   47.255475
14               Indiana   46.536191
3               Arkansas   46.242862
41          South Dakota   45.379609
18             Louisiana   43.609940
13              Illinois   43.434628
0                Alabama   42.820017
34          North Dakota   42.336173
10               Georgia   41.680247
25              Missouri   41.675716
42             Tennessee   41.290392
17              Kentucky   40.559536
24           Mississippi   39.032636
43                 Texas   38.642216
36              Oklahoma   36.125244

In [7]:
#% Nurse midwives per capita [county] — MIDWIVESrate 

state_midwives_avg = merged_df.groupby('state')['MIDWIVESrate'].mean().reset_index()
state_midwives_avg = state_midwives_avg.sort_values(by='MIDWIVESrate', ascending=False)
state_midwives_avg 

#❓ to Dhrumil -- can I count the state average like this? -- just counting average counties's rate?

                   state  MIDWIVESrate
45               Vermont     17.983492
8   District of Columbia     17.071948
29         New Hampshire     16.693935
21         Massachusetts     12.419976
19                 Maine     11.891615
6            Connecticut      8.233683
7               Delaware      7.794816
1                 Alaska      7.467405
2                Arizona      7.037959
20              Maryland      6.963955
37                Oregon      6.791551
32              New York      6.566167
31            New Mexico      6.325967
39          Rhode Island      6.207589
5               Colorado      5.909791
30            New Jersey      5.326724
38          Pennsylvania      5.301884
50               Wyoming      5.064228
33        North Carolina      4.909582
41          South Dakota      4.664801
23             Minnesota      4.540130
47            Washington      4.452904
46              Virginia      4.180631
11                Hawaii      4.139655
44                  Utah      4.123781
49             Wisconsin      4.072050
4             California      4.016161
9                Florida      3.934886
10               Georgia      3.600539
22              Michigan      3.344837
15                  Iowa      3.135258
35                  Ohio      3.114991
13              Illinois      3.064575
48         West Virginia      2.889250
12                 Idaho      2.794248
17              Kentucky      2.623844
14               Indiana      2.479936
42             Tennessee      2.183102
36              Oklahoma      2.131013
40        South Carolina      2.081316
26               Montana      1.992535
16                Kansas      1.543269
34          North Dakota      1.163204
25              Missouri      1.088105
24           Mississippi      1.041013
43                 Texas      0.899734
28                Nevada      0.806975
27              Nebraska      0.763487
0                Alabama      0.683526
18             Louisiana      0.493488
3               Arkansas      0.392444

In [9]:
state_mhproviders_avg = merged_df.groupby('state')['MHPROVIDERrate'].mean().reset_index()
state_mhproviders_avg = state_mhproviders_avg.sort_values(by='MHPROVIDERrate', ascending=False)
state_mhproviders_avg

                   state  MHPROVIDERrate
1                 Alaska       10.576916
36              Oklahoma        9.312264
2                Arizona        8.823778
26               Montana        8.212617
37                Oregon        7.999651
6            Connecticut        7.399321
45               Vermont        6.871705
8   District of Columbia        6.706962
31            New Mexico        6.219558
23             Minnesota        6.073282
44                  Utah        5.770416
20              Maryland        5.538541
34          North Dakota        5.523732
41          South Dakota        5.419676
50               Wyoming        5.272121
15                  Iowa        5.033076
5               Colorado        4.916735
49             Wisconsin        4.716766
22              Michigan        4.675149
25              Missouri        4.337825
47            Washington        4.309953
17              Kentucky        4.308842
28                Nevada        3.899108
12                 Idaho        3.802449
19                 Maine        3.730937
48         West Virginia        3.594060
13              Illinois        3.323610
46              Virginia        3.019620
3               Arkansas        2.913549
35                  Ohio        2.863612
32              New York        2.810957
29         New Hampshire        2.698828
39          Rhode Island        2.581255
27              Nebraska        2.521062
33        North Carolina        2.466353
18             Louisiana        2.325358
11                Hawaii        2.226098
40        South Carolina        2.073554
14               Indiana        1.969201
4             California        1.644226
7               Delaware        1.611215
9                Florida        1.518411
16                Kansas        1.444198
38          Pennsylvania        1.268153
24           Mississippi        1.252448
0                Alabama        1.085114
10               Georgia        1.039459
21         Massachusetts        1.032397
42             Tennessee        0.833942
43                 Texas        0.521315
30            New Jersey        0.486240